### ISSUE TITLE
SmartThings page > Theater, Office, Back Room and Bedroom tabs have messed fields

### ISSUE THREAD

**Issue by popescunsergiu** [RoboDomo/robodomo-client#25] opened 2019-07-19 13:02 UTC
*Env:* Latest master

*Steps to reproduce:*
1. Go to SmartThings > Theater tab

*Actual Results:*
Entryway, Office and Kitchen related elements are present in this tab
![Screenshot 2019-07-19 at 15 57 17](https://user-images.githubusercontent.com/8069082/61536793-29f30f00-aa3e-11e9-9c67-2e7118824a02.png)

*Steps to reproduce:*
1. Go to SmartThings > Office tab

*Actual Results:*
Entryway related elements are present in this tab
![Screenshot 2019-07-19 at 16 00 09](https://user-images.githubusercontent.com/8069082/61536865-560e9000-aa3e-11e9-9e2b-e93cd33f4141.png)

*Steps to reproduce:*
1. Go to SmartThings > Back Room tab

*Actual Results:*
Entryway and Office related elements are present in this tab
![Screenshot 2019-07-19 at 16 01 07](https://user-images.githubusercontent.com/8069082/61536911-78081280-aa3e-11e9-936a-d1f204ac5aae.png)

*Steps to reproduce:*
1. Go to SmartThings > Bedroom tab

*Actual Results:*
Entryway, Front, Kitchen, Bathroom related elements are present in this tab
![Screenshot 2019-07-19 at 16 01 40](https://user-images.githubusercontent.com/8069082/61536954-8ce4a600-aa3e-11e9-8308-d3c24ce39644.png)

**Comment by mschwartz** [comment] 2019-07-24 18:17
This is by design.

In the Config object, you select the SmartThings items and what rooms (tabs) they are to appear on.  A thing can appear on multiple tabs.

The idea is that, for example, the theater tab SHOULD have kitchen light control because the kitchen light is sometimes involved in theater usage.  I mean, when the kitchen light is on, I want to turn it off while watching TV on the couch :)

I recommend closing this.

**Closed** 2019-08-02 15:18 UTC
